<?php $pagetitle="Welcome to Epic Photographpy"; ?>
<?php include 'header.php'; ?>
<p>Epic Photography provides a large collection of High Resolution Photos that look great in a desktop background slideshow. My site will provide images that have superior quality compared to others The Photos on this site have been handpicked by me for their beauty over the past five years. I only select natural images: scenic pictures, macro close up images, and Astronomy Pictures. But other people should have an epic background slideshow, this website will allow anyone to download the images and use them on their own machine</p>
<p>We cannot <a href="#">ignorei</a> that we have a right and a duty to protect our borders. This was one of the tasks we set forth at the beginning of this campaign - to continue the long march of those who came before us, a march for a more just, more equal, more free, more caring and more prosperous America. But it also means binding our particular grievances - for better health care, and better schools, and better jobs - to the larger aspirations of all Americans - the white woman struggling to break the glass ceiling, the white man whose been laid off, the immigrant trying to feed his family. In the face of that young student who sleeps just three hours before working the night shift, I think about my mom, who raised my sister and me on her own while she worked and earned her degree; who once turned to food stamps but was still able to send us to the best schools in the country with the help of student loans and scholarships. And it is on their behalf that I intend to win this election and keep our promise alive as President of the United States. I am honored to be in the timeless city of Cairo, and to be hosted by two remarkable institutions. </p>
<p>Many bring up a specific issue. They have not served a Red America or a Blue America - they have served the United States of America. The sooner the extremists are isolated and unwelcome in Muslim communities, the sooner we will all be safer. </p>
<p>And the lack of basic services in so many urban black neighborhoods - parks for kids to play in, police walking the beat, regular garbage pick-up and building code enforcement - all helped create a cycle of violence, blight and neglect that continue to haunt us. I'll invest in early childhood education. The attacks of September 11th, 2001 and the continued efforts of these extremists to engage in violence against civilians has led some in my country to view Islam as inevitably hostile not only to America and Western countries, but also to human rights. I do so recognizing that change cannot happen overnight. I am a Christian, but my father came from a Kenyan family that includes generations of Muslims. </p>
<p>Our conscience can't rest so long as 37 million Americans are poor and forgotten by their leaders in Washington and by the media elites. And we should close Guantanamo Bay and stop tolerating the torture of our enemies. If your hopes have been dashed again and again, then it's best to stop hoping, and settle for what you already know. "And as we walk, we must make the pledge that we shall always march ahead. We cannot turn back." The Holy Koran teaches that whoever kills an innocent, it is as if he has killed all mankind; and whoever saves a person, it is as if he has saved all mankind. </p>
<p>You know, a while back, I met a young man named Shamus [Seamus?] in a V.F.W. The questions I had didn't magically disappear. I'm hearing from evangelicals who may not agree with progressives on every issue but agree that poverty has no place in a world of plenty; that hate has no place in the hearts of believers; and that we all have to be good stewards of God's creations. It was stained by this nation's original sin of slavery, a question that divided the colonies and brought the convention to a stalemate until the founders chose to allow the slave trade to continue for at least twenty more years, and to leave any final resolution to future generations. And in exchange, I'll ask for higher standards and more accountability. The issues that I have described will not be easy to address. </p>
<p>But it also comes from my own American story. Just as black anger often proved counterproductive, so have these white resentments distracted attention from the real culprits of the middle class squeeze - a corporate culture rife with inside dealing, questionable accounting practices, and short-term greed; a Washington dominated by lobbyists and special interests; economic policies that favor the few over the many. Four years ago, I stood before you and told you my story - of the brief union between a young man from Kenya and a young woman from Kansas who weren't well-off or well-known, but shared a belief that in America, their son could achieve whatever he put his mind to. Those are not just American ideas, they are human rights, and that is why we will support them everywhere. </p>
<p>Some will see this as an attempt to justify or excuse comments that are simply inexcusable. Indeed, faith should bring us together. </p>
<p>He told me he'd joined the Marines, and was heading to Iraq the following week. In my first book, Dreams From My Father, I described the experience of my first service at Trinity: I can assure you it is not. It is where our union grows stronger. That experience guides my conviction that partnership between America and Islam must be based on what Islam is, not what it isn't. So America will defend itself respectful of the sovereignty of nations and the rule of law. </p>
<p>He was a good-looking kid, six two, six three, clear eyed, with an easy smile. And all across the country, communities of faith are sponsoring day care programs, building senior centers, and in so many other ways, taking part in the project of American renewal. Universities and states, including Illinois, are taking part in a divestment campaign to pressure the Sudanese government to stop the killings. Even for those blacks who did make it, questions of race, and racism, continue to define their worldview in fundamental ways. They work hard and give back and keep going without complaint. Now is the time to help families with paid sick days and better family leave, because nobody in America should have to choose between keeping their jobs and caring for a sick child or ailing parent. </p>
<p>I'm hearing from evangelicals who may not agree with progressives on every issue but agree that poverty has no place in a world of plenty; that hate has no place in the hearts of believers; and that we all have to be good stewards of God's creations. We can tackle race only as spectacle - as we did in the OJ trial - or in the wake of tragedy, as we did in the aftermath of Katrina - or as fodder for the nightly news. Perhaps somebody told her along the way that the source of her mother's problems were blacks who were on welfare and too lazy to work, or Hispanics who were coming into the country illegally. They have killed people of different faiths - more than any other, they have killed Muslims. And just as it devastates Palestinian families, the continuing humanitarian crisis in Gaza does not serve Israel's security; neither does the continuing lack of opportunity in the West Bank. </p>
<p>They imagined me going to the best schools in the land, even though they weren't rich, because in a generous America you don't have to be rich to achieve your potential. He does not say that he was there because of Barack Obama. And I will not settle for an America where some kids don't have that chance. </p>
<p>That's the change we need right now. But I will also go through the federal budget, line by line, eliminating programs that no longer work and making the ones we do need work better and cost less - because we cannot meet twenty-first century challenges with a twentieth century bureaucracy. You understand that in this election, the greatest risk we can take is to try the same old politics with the same old players and expect a different result. </p>
<p>Anyway, Ashley finishes her story and then goes around the room and asks everyone else why they're supporting the campaign. It is that promise that has always set this country apart - that through hard work and sacrifice, each of us can pursue our individual dreams but still come together as one American family, to ensure that the next generation can pursue their dreams as well. On November 4th, we must stand up and say: "Eight is enough." </p>
<p>I have a plan that would have already begun redeploying our troops with the goal of bringing all our combat brigades home by March 31st of next year. They work hard and give back and keep going without complaint. Now is the time to finally meet our moral obligation to provide every child a world-class education, because it will take nothing less to compete in the global economy. But I will also go through the federal budget, line by line, eliminating programs that no longer work and making the ones we do need work better and cost less - because we cannot meet twenty-first century challenges with a twentieth century bureaucracy. Not with so much work to be done. So let there be no doubt: the situation for the Palestinian people is intolerable. </p>
<p>And they, too, had big dreams for their daughter. These people are a part of me. And today, whenever I find myself feeling doubtful or cynical about this possibility, what gives me the most hope is the next generation - the young people whose attitudes and beliefs and openness to change have already made history in this election. </p>
<p>Now even as we speak, there are those who are preparing to divide us, the spin masters, the negative ad peddlers who embrace the politics of anything goes. A belief that there are better days ahead. Our conscience cannot rest until we not only secure our borders, but give the 12 million undocumented immigrants in this country a chance to earn their citizenship by paying a fine and waiting in line behind all those who came here legally. And I've seen it in this campaign. So long as our relationship is defined by our differences, we will empower those who sow hatred rather than peace, and who promote conflict rather than the cooperation that can help all of our people achieve justice and prosperity. </p>
<p>I'm talking about something more substantial. They have fought in our wars, served in government, stood for civil rights, started businesses, taught at our Universities, excelled in our sports arenas, won Nobel Prizes, built our tallest building, and lit the Olympic Torch. Our daughters can contribute just as much to society as our sons, and our common prosperity will be advanced by allowing all humanity - men and women - to reach their full potential. </p>
<p>But then I asked myself: Are we serving Shamus as well as he is serving us? It's not enough, but it's helping. It's a war I'm proud I opposed from the start - a war that should never have been authorized and never been waged. That is why the U.S. The first issue that we have to confront is violent extremism in all of its forms. </p>
<p>And fellow Americans, Democrats, Republicans, Independents - I say to you tonight: we have more work to do. They want a sense of purpose, a narrative arc to their lives. This is a problem that's brought together churches and synagogues and mosques and people of all faiths as part of a grassroots movement. </p>
<p>I love this country, and so do you, and so does John McCain. Instead, it is that American spirit - that American promise - that pushes us forward even when the path is uncertain; that binds us together in spite of our differences; that makes us fix our eye not on what is seen, but what is unseen, that better place around the bend. In Ankara, I made clear that America is not - and never will be - at war with Islam. </p>
<p>God bless you. </p>
<?php include 'footer.php'; ?>
